/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gn1uZlGlwG5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import {usePrivy, useWallets} from "@privy-io/react-auth";
import {useAccount, useDisconnect} from "wagmi";
import {useSetActiveWallet} from "@privy-io/wagmi";

export function StakeComponent() {


  // Privy hooks
  const {ready, user, authenticated, login, connectWallet, logout, linkWallet} = usePrivy();
  const {wallets, ready: walletsReady} = useWallets();

  // WAGMI hooks
  const {address, isConnected, isConnecting, isDisconnected} = useAccount();
  const {disconnect} = useDisconnect();
  const {setActiveWallet} = useSetActiveWallet();

  if (!ready) {
    return null;
  }

  return (
    <div className="flex min-h-screen w-full flex-col bg-background text-foreground">
      <header className="sticky top-0 z-20 border-b bg-background px-4 py-3 sm:px-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <LeafIcon className="h-6 w-6 text-primary" />
            <span className="font-bold">SEED Staking</span>
          </Link>
          <div className="flex items-center gap-4">
            <Button variant="outline">Connect Wallet</Button>
          </div>
        </div>
      </header>
      <main className="flex-1 px-4 py-8 sm:px-6">
        <div className="container mx-auto grid max-w-4xl grid-cols-1 gap-8 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Stake SEED</CardTitle>
              <CardDescription>Stake your SEED tokens to earn LEAF token rewards.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="stake-amount">Amount to Stake</Label>
                  <div className="flex items-center gap-2">
                    <Input id="stake-amount" type="number" placeholder="0" min="0" step="0.01" className="flex-1" />
                    <Button variant="outline">MAX</Button>
                  </div>
                </div>
                <Button className="w-full">Stake</Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Claim LEAF</CardTitle>
              <CardDescription>Claim your LEAF token rewards from staking SEED.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <div className="flex items-center justify-between">
                    <span>Available LEAF Rewards</span>
                    <span className="font-medium">10.25 LEAF</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Total LEAF Balance</span>
                    <span className="font-medium">25.50 LEAF</span>
                  </div>
                </div>
                <Button className="w-full">Claim Rewards</Button>
              </div>
            </CardContent>
          </Card>
          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>My Staking</CardTitle>
              <CardDescription>View your staked SEED tokens and earned LEAF rewards.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <div className="flex items-center justify-between">
                    <span>Staked SEED</span>
                    <span className="font-medium">100.00 SEED</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Available LEAF Rewards</span>
                    <span className="font-medium">10.25 LEAF</span>
                  </div>
                </div>
                <div className="grid gap-2">
                  <Button variant="outline" className="w-full">
                    Unstake SEED
                  </Button>
                  <Button className="w-full">Claim LEAF</Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
      <footer className="border-t bg-background px-4 py-4 sm:px-6">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm text-muted-foreground">&copy; 2024 SEED Staking. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Privacy Policy
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function LeafIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
    </svg>
  )
}
